apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - imageName: gcr.io/istio-next/emailservice
    workspace: src/emailservice
  - imageName: gcr.io/istio-next/productcatalogservice
    workspace: src/productcatalogservice
  - imageName: gcr.io/istio-next/recommendationservice
    workspace: src/recommendationservice
  - imageName: gcr.io/istio-next/shippingservice
    workspace: src/shippingservice
  - imageName: gcr.io/istio-next/checkoutservice
    workspace: src/checkoutservice
  - imageName: gcr.io/istio-next/paymentservice
    workspace: src/paymentservice
  - imageName: gcr.io/istio-next/currencyservice
    workspace: src/currencyservice
  - imageName: gcr.io/istio-next/cartservice
    workspace: src/cartservice
  - imageName: gcr.io/istio-next/frontend
    workspace: src/frontend
  - imageName: gcr.io/istio-next/loadgenerator
    workspace: src/loadgenerator
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
