apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - imageName: gcr.io/hipstershop-demo/emailservice
    workspace: src/emailservice
  - imageName: gcr.io/hipstershop-demo/productcatalogservice
    workspace: src/productcatalogservice
  - imageName: gcr.io/hipstershop-demo/recommendationservice
    workspace: src/recommendationservice
  - imageName: gcr.io/hipstershop-demo/shippingservice
    workspace: src/shippingservice
  - imageName: gcr.io/hipstershop-demo/checkoutservice
    workspace: src/checkoutservice
  - imageName: gcr.io/hipstershop-demo/paymentservice
    workspace: src/paymentservice
  - imageName: gcr.io/hipstershop-demo/currencyservice
    workspace: src/currencyservice
  - imageName: gcr.io/hipstershop-demo/cartservice
    workspace: src/cartservice
  - imageName: gcr.io/hipstershop-demo/frontend
    workspace: src/frontend
  - imageName: gcr.io/hipstershop-demo/loadgenerator
    workspace: src/loadgenerator
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
