# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ms_demo_mail_service_pb2 as ms__demo__mail__service__pb2


class EmailServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendOrderConfirmation = channel.unary_unary(
        '/EmailService/SendOrderConfirmation',
        request_serializer=ms__demo__mail__service__pb2.SendOrderConfirmationRequest.SerializeToString,
        response_deserializer=ms__demo__mail__service__pb2.Empty.FromString,
        )


class EmailServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendOrderConfirmation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EmailServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendOrderConfirmation': grpc.unary_unary_rpc_method_handler(
          servicer.SendOrderConfirmation,
          request_deserializer=ms__demo__mail__service__pb2.SendOrderConfirmationRequest.FromString,
          response_serializer=ms__demo__mail__service__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'EmailService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
