apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cartservice
spec:
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      terminationGracePeriodSeconds: 5
      initContainers:
      - name: wait-redis
        image: redis:alpine
        command: ['sh', '-c', 'set -x;
          until timeout -t 5 redis-cli -h "${REDIS_HOST}" -p "${REDIS_PORT}" ping; do
            echo "waiting for redis at ${REDIS_HOST}:${REDIS_PORT}...";
            sleep 2;
          done;']
        env:
        - name: REDIS_HOST
          value: "redis-cart"
        - name: REDIS_PORT
          value: "6379"
      containers:
      - name: server
        image: cartservice
        ports:
        - containerPort: 7070
        env:
        - name: REDIS_ADDR
          value: "redis-cart:6379"
        - name: PORT
          value: "7070"
        - name: LISTEN_ADDR
          value: "0.0.0.0"
        # - name: GRPC_TRACE
        #   value: "all"
        # - name: GRPC_VERBOSITY
        #   value: "debug"
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 128Mi
        readinessProbe:
          tcpSocket:
             port: 7070
        livenessProbe:
          tcpSocket:
             port: 7070
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
spec:
  type: ClusterIP
  selector:
    app: cartservice
  ports:
  - port: 7070
    targetPort: 7070
