apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: currencyservice
spec:
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
      - name: server
        image: currencyservice
        ports:
        - containerPort: 31337
        readinessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 31337
        livenessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 31337
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
spec:
  type: ClusterIP
  selector:
    app: currencyservice
  ports:
  - port: 7000
    targetPort: 31337
