apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: emailservice
spec:
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: emailservice
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 8080
        livenessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 8080
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
spec:
  type: ClusterIP
  selector:
    app: emailservice
  ports:
  - port: 5000
    targetPort: 8080
