apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: paymentservice
spec:
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: gcr.io/hipstershop-demo/paymentservice
        ports:
        - containerPort: 50051
        readinessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 50051
        livenessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 50051
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
spec:
  type: ClusterIP
  selector:
    app: paymentservice
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
