apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: productcatalogservice
spec:
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      containers:
      - name: server
        image: productcatalogservice
        ports:
        - containerPort: 3550
        readinessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 3550
        livenessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 3550
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
spec:
  type: ClusterIP
  selector:
    app: productcatalogservice
  ports:
  - port: 3550
    targetPort: 3550
