apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: recommendationservice
spec:
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: gcr.io/istio-next/recommendationservice
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 8080
        livenessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 8080
        env:
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:3550"
        resources:
          requests:
            cpu: 100m
            memory: 220Mi
          limits:
            cpu: 200m
            memory: 450Mi
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
spec:
  type: ClusterIP
  selector:
    app: recommendationservice
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
