apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shippingservice
spec:
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
      - name: server
        image: shippingservice
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
spec:
  type: ClusterIP
  selector:
    app: shippingservice
  ports:
  - port: 50051
    targetPort: 50051
