# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/mail_v1alpha3/proto/address_set.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/cloud/mail_v1alpha3/proto/address_set.proto',
  package='google.cloud.mail.v1alpha3',
  syntax='proto3',
  serialized_pb=_b('\n2google/cloud/mail_v1alpha3/proto/address_set.proto\x12\x1agoogle.cloud.mail.v1alpha3\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd8\x01\n\nAddressSet\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65leted\x18\x02 \x01(\x08\x12\x18\n\x10\x61\x64\x64ress_patterns\x18\x03 \x03(\t\x12/\n\x0b\x63reate_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0bupdate_time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0b\x64\x65lete_time\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\">\n\x16ListAddressSetsRequest\x12\x0e\n\x06parent\x18\x01 \x01(\t\x12\x14\n\x0cshow_deleted\x18\x02 \x01(\x08\"W\n\x17ListAddressSetsResponse\x12<\n\x0c\x61\x64\x64ress_sets\x18\x01 \x03(\x0b\x32&.google.cloud.mail.v1alpha3.AddressSet\"$\n\x14GetAddressSetRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"~\n\x17\x43reateAddressSetRequest\x12\x0e\n\x06parent\x18\x01 \x01(\t\x12\x16\n\x0e\x61\x64\x64ress_set_id\x18\x02 \x01(\t\x12;\n\x0b\x61\x64\x64ress_set\x18\x03 \x01(\x0b\x32&.google.cloud.mail.v1alpha3.AddressSet\"\x87\x01\n\x17UpdateAddressSetRequest\x12;\n\x0b\x61\x64\x64ress_set\x18\x01 \x01(\x0b\x32&.google.cloud.mail.v1alpha3.AddressSet\x12/\n\x0bupdate_mask\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.FieldMask\"\'\n\x17\x44\x65leteAddressSetRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\")\n\x19UndeleteAddressSetRequest\x12\x0c\n\x04name\x18\x01 \x01(\tB|\n\x1e\x63om.google.cloud.mail.v1alpha3B\x0f\x41\x64\x64ressSetProtoP\x01Z>google.golang.org/genproto/googleapis/cloud/mail/v1alpha3;mail\xf8\x01\x01\xa2\x02\x03GCMb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_field__mask__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_ADDRESSSET = _descriptor.Descriptor(
  name='AddressSet',
  full_name='google.cloud.mail.v1alpha3.AddressSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='google.cloud.mail.v1alpha3.AddressSet.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deleted', full_name='google.cloud.mail.v1alpha3.AddressSet.deleted', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address_patterns', full_name='google.cloud.mail.v1alpha3.AddressSet.address_patterns', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='create_time', full_name='google.cloud.mail.v1alpha3.AddressSet.create_time', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='update_time', full_name='google.cloud.mail.v1alpha3.AddressSet.update_time', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delete_time', full_name='google.cloud.mail.v1alpha3.AddressSet.delete_time', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=366,
)


_LISTADDRESSSETSREQUEST = _descriptor.Descriptor(
  name='ListAddressSetsRequest',
  full_name='google.cloud.mail.v1alpha3.ListAddressSetsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parent', full_name='google.cloud.mail.v1alpha3.ListAddressSetsRequest.parent', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='show_deleted', full_name='google.cloud.mail.v1alpha3.ListAddressSetsRequest.show_deleted', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=430,
)


_LISTADDRESSSETSRESPONSE = _descriptor.Descriptor(
  name='ListAddressSetsResponse',
  full_name='google.cloud.mail.v1alpha3.ListAddressSetsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address_sets', full_name='google.cloud.mail.v1alpha3.ListAddressSetsResponse.address_sets', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=432,
  serialized_end=519,
)


_GETADDRESSSETREQUEST = _descriptor.Descriptor(
  name='GetAddressSetRequest',
  full_name='google.cloud.mail.v1alpha3.GetAddressSetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='google.cloud.mail.v1alpha3.GetAddressSetRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=521,
  serialized_end=557,
)


_CREATEADDRESSSETREQUEST = _descriptor.Descriptor(
  name='CreateAddressSetRequest',
  full_name='google.cloud.mail.v1alpha3.CreateAddressSetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parent', full_name='google.cloud.mail.v1alpha3.CreateAddressSetRequest.parent', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address_set_id', full_name='google.cloud.mail.v1alpha3.CreateAddressSetRequest.address_set_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address_set', full_name='google.cloud.mail.v1alpha3.CreateAddressSetRequest.address_set', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=559,
  serialized_end=685,
)


_UPDATEADDRESSSETREQUEST = _descriptor.Descriptor(
  name='UpdateAddressSetRequest',
  full_name='google.cloud.mail.v1alpha3.UpdateAddressSetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address_set', full_name='google.cloud.mail.v1alpha3.UpdateAddressSetRequest.address_set', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='update_mask', full_name='google.cloud.mail.v1alpha3.UpdateAddressSetRequest.update_mask', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=688,
  serialized_end=823,
)


_DELETEADDRESSSETREQUEST = _descriptor.Descriptor(
  name='DeleteAddressSetRequest',
  full_name='google.cloud.mail.v1alpha3.DeleteAddressSetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='google.cloud.mail.v1alpha3.DeleteAddressSetRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=825,
  serialized_end=864,
)


_UNDELETEADDRESSSETREQUEST = _descriptor.Descriptor(
  name='UndeleteAddressSetRequest',
  full_name='google.cloud.mail.v1alpha3.UndeleteAddressSetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='google.cloud.mail.v1alpha3.UndeleteAddressSetRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=866,
  serialized_end=907,
)

_ADDRESSSET.fields_by_name['create_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_ADDRESSSET.fields_by_name['update_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_ADDRESSSET.fields_by_name['delete_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_LISTADDRESSSETSRESPONSE.fields_by_name['address_sets'].message_type = _ADDRESSSET
_CREATEADDRESSSETREQUEST.fields_by_name['address_set'].message_type = _ADDRESSSET
_UPDATEADDRESSSETREQUEST.fields_by_name['address_set'].message_type = _ADDRESSSET
_UPDATEADDRESSSETREQUEST.fields_by_name['update_mask'].message_type = google_dot_protobuf_dot_field__mask__pb2._FIELDMASK
DESCRIPTOR.message_types_by_name['AddressSet'] = _ADDRESSSET
DESCRIPTOR.message_types_by_name['ListAddressSetsRequest'] = _LISTADDRESSSETSREQUEST
DESCRIPTOR.message_types_by_name['ListAddressSetsResponse'] = _LISTADDRESSSETSRESPONSE
DESCRIPTOR.message_types_by_name['GetAddressSetRequest'] = _GETADDRESSSETREQUEST
DESCRIPTOR.message_types_by_name['CreateAddressSetRequest'] = _CREATEADDRESSSETREQUEST
DESCRIPTOR.message_types_by_name['UpdateAddressSetRequest'] = _UPDATEADDRESSSETREQUEST
DESCRIPTOR.message_types_by_name['DeleteAddressSetRequest'] = _DELETEADDRESSSETREQUEST
DESCRIPTOR.message_types_by_name['UndeleteAddressSetRequest'] = _UNDELETEADDRESSSETREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddressSet = _reflection.GeneratedProtocolMessageType('AddressSet', (_message.Message,), dict(
  DESCRIPTOR = _ADDRESSSET,
  __module__ = 'google.cloud.mail_v1alpha3.proto.address_set_pb2'
  ,
  __doc__ = """A specification of a set of email addresses within a domain. These are
  created by the domain administrator to delegate permission to send from
  a set of addresses.
  
  
  Attributes:
      name:
          The name of the AddressSet resource, like "regions/us-
          east1/domains/1234/addressSets/xyz".
      deleted:
          True if the resource has been deleted.
      address_patterns:
          Regular expressions of email address local parts matched by
          this AddressSet. There can be at most 100. The "local part" is
          the part of the email address before the @. In order to match
          this AddressSet, an email address's domain must be the same as
          the domain\_name of the parent Domain, and its local part must
          match one of these regular expressions.
      create_time:
          The creation timestamp.
      update_time:
          The last modified timestamp, set during create, update,
          delete, or undelete.
      delete_time:
          The time the resource was marked deleted.
  """,
  # @@protoc_insertion_point(class_scope:google.cloud.mail.v1alpha3.AddressSet)
  ))
_sym_db.RegisterMessage(AddressSet)

ListAddressSetsRequest = _reflection.GeneratedProtocolMessageType('ListAddressSetsRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTADDRESSSETSREQUEST,
  __module__ = 'google.cloud.mail_v1alpha3.proto.address_set_pb2'
  ,
  __doc__ = """Request for CloudMail.ListAddressSets
  
  
  Attributes:
      parent:
          Name of the domain whose AddressSets are to be retrieved, like
          "regions/us-east1/domains/1234".
      show_deleted:
          Indicates if user wants to list deleted AddressSets
  """,
  # @@protoc_insertion_point(class_scope:google.cloud.mail.v1alpha3.ListAddressSetsRequest)
  ))
_sym_db.RegisterMessage(ListAddressSetsRequest)

ListAddressSetsResponse = _reflection.GeneratedProtocolMessageType('ListAddressSetsResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTADDRESSSETSRESPONSE,
  __module__ = 'google.cloud.mail_v1alpha3.proto.address_set_pb2'
  ,
  __doc__ = """Response for CloudMail.ListAddressSets
  
  
  Attributes:
      address_sets:
          The list of AddressSets matching
          ListAddressSetsRequest.parent.
  """,
  # @@protoc_insertion_point(class_scope:google.cloud.mail.v1alpha3.ListAddressSetsResponse)
  ))
_sym_db.RegisterMessage(ListAddressSetsResponse)

GetAddressSetRequest = _reflection.GeneratedProtocolMessageType('GetAddressSetRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETADDRESSSETREQUEST,
  __module__ = 'google.cloud.mail_v1alpha3.proto.address_set_pb2'
  ,
  __doc__ = """Request for CloudMail.GetAddressSet
  
  
  Attributes:
      name:
          Name of the AddressSet to retrieve, like "regions/us-
          east1/domains/1234/addressSets/xyz".
  """,
  # @@protoc_insertion_point(class_scope:google.cloud.mail.v1alpha3.GetAddressSetRequest)
  ))
_sym_db.RegisterMessage(GetAddressSetRequest)

CreateAddressSetRequest = _reflection.GeneratedProtocolMessageType('CreateAddressSetRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATEADDRESSSETREQUEST,
  __module__ = 'google.cloud.mail_v1alpha3.proto.address_set_pb2'
  ,
  __doc__ = """Request for CloudMail.CreateAddressSet
  
  
  Attributes:
      parent:
          Name of the domain to create the receipt rule for, like
          "regions/us-east1/domains/1234".
      address_set_id:
          Optional client-assigned name for the address set. If not
          specified, a random name will be assigned by the server. If
          specified, the ID must be an ASCII string consisting only of
          uppercase and lowercase letters, digits, and hyphens. The
          maximum length is 128 bytes.
      address_set:
          The AddressSet to create.
  """,
  # @@protoc_insertion_point(class_scope:google.cloud.mail.v1alpha3.CreateAddressSetRequest)
  ))
_sym_db.RegisterMessage(CreateAddressSetRequest)

UpdateAddressSetRequest = _reflection.GeneratedProtocolMessageType('UpdateAddressSetRequest', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEADDRESSSETREQUEST,
  __module__ = 'google.cloud.mail_v1alpha3.proto.address_set_pb2'
  ,
  __doc__ = """Request for CloudMail.UpdateAddressSet
  
  
  Attributes:
      address_set:
          The AddressSet that replaces the resource on the server.
      update_mask:
          Which fields of the address\_set to update.
  """,
  # @@protoc_insertion_point(class_scope:google.cloud.mail.v1alpha3.UpdateAddressSetRequest)
  ))
_sym_db.RegisterMessage(UpdateAddressSetRequest)

DeleteAddressSetRequest = _reflection.GeneratedProtocolMessageType('DeleteAddressSetRequest', (_message.Message,), dict(
  DESCRIPTOR = _DELETEADDRESSSETREQUEST,
  __module__ = 'google.cloud.mail_v1alpha3.proto.address_set_pb2'
  ,
  __doc__ = """Request for CloudMail.DeleteAddressSet
  
  
  Attributes:
      name:
          Name of the AddressSet to delete, like "regions/us-
          east1/domains/1234/addressSets/xyz".
  """,
  # @@protoc_insertion_point(class_scope:google.cloud.mail.v1alpha3.DeleteAddressSetRequest)
  ))
_sym_db.RegisterMessage(DeleteAddressSetRequest)

UndeleteAddressSetRequest = _reflection.GeneratedProtocolMessageType('UndeleteAddressSetRequest', (_message.Message,), dict(
  DESCRIPTOR = _UNDELETEADDRESSSETREQUEST,
  __module__ = 'google.cloud.mail_v1alpha3.proto.address_set_pb2'
  ,
  __doc__ = """Request for CloudMail.UndeleteAddressSet
  
  
  Attributes:
      name:
          Name of the AddressSet to undelete, like "regions/us-
          east1/domains/1234/addressSets/xyz".
  """,
  # @@protoc_insertion_point(class_scope:google.cloud.mail.v1alpha3.UndeleteAddressSetRequest)
  ))
_sym_db.RegisterMessage(UndeleteAddressSetRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\036com.google.cloud.mail.v1alpha3B\017AddressSetProtoP\001Z>google.golang.org/genproto/googleapis/cloud/mail/v1alpha3;mail\370\001\001\242\002\003GCM'))
# @@protoc_insertion_point(module_scope)
