# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.cloud.mail_v1alpha3.proto import address_set_pb2 as google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_address__set__pb2
from google.cloud.mail_v1alpha3.proto import domain_pb2 as google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2
from google.cloud.mail_v1alpha3.proto import email_verified_address_pb2 as google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2
from google.cloud.mail_v1alpha3.proto import receipt_rule_pb2 as google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_receipt__rule__pb2
from google.cloud.mail_v1alpha3.proto import sender_pb2 as google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_sender__pb2
from google.cloud.mail_v1alpha3.proto import smtp_credential_pb2 as google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_smtp__credential__pb2
from google.iam.v1 import iam_policy_pb2 as google_dot_iam_dot_v1_dot_iam__policy__pb2
from google.iam.v1 import policy_pb2 as google_dot_iam_dot_v1_dot_policy__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class CloudMailStub(object):
  """Provides Google Cloud Mail customers a way to manage the service and to send
  mail.  Use this to add or remove domains, define handling for incoming
  messages, and register senders for outbound messages.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListDomains = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/ListDomains',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.ListDomainsRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.ListDomainsResponse.FromString,
        )
    self.GetDomain = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/GetDomain',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.GetDomainRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.Domain.FromString,
        )
    self.CreateDomain = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/CreateDomain',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.CreateDomainRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.Domain.FromString,
        )
    self.UpdateDomain = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/UpdateDomain',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.UpdateDomainRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.Domain.FromString,
        )
    self.DeleteDomain = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/DeleteDomain',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.DeleteDomainRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.Domain.FromString,
        )
    self.UndeleteDomain = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/UndeleteDomain',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.UndeleteDomainRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.Domain.FromString,
        )
    self.TestReceiptRules = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/TestReceiptRules',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.TestReceiptRulesRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.TestReceiptRulesResponse.FromString,
        )
    self.VerifyDomain = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/VerifyDomain',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.VerifyDomainRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.Domain.FromString,
        )
    self.ListEmailVerifiedAddresses = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/ListEmailVerifiedAddresses',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.ListEmailVerifiedAddressesRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.ListEmailVerifiedAddressesResponse.FromString,
        )
    self.GetEmailVerifiedAddress = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/GetEmailVerifiedAddress',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.GetEmailVerifiedAddressRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.EmailVerifiedAddress.FromString,
        )
    self.CreateEmailVerifiedAddress = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/CreateEmailVerifiedAddress',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.CreateEmailVerifiedAddressRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.EmailVerifiedAddress.FromString,
        )
    self.UpdateEmailVerifiedAddress = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/UpdateEmailVerifiedAddress',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.UpdateEmailVerifiedAddressRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.EmailVerifiedAddress.FromString,
        )
    self.DeleteEmailVerifiedAddress = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/DeleteEmailVerifiedAddress',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.DeleteEmailVerifiedAddressRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.EmailVerifiedAddress.FromString,
        )
    self.UndeleteEmailVerifiedAddress = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/UndeleteEmailVerifiedAddress',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.UndeleteEmailVerifiedAddressRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.EmailVerifiedAddress.FromString,
        )
    self.RequestEmailVerification = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/RequestEmailVerification',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.RequestEmailVerificationRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.RequestEmailVerificationResponse.FromString,
        )
    self.VerifyEmail = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/VerifyEmail',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.VerifyEmailRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.EmailVerifiedAddress.FromString,
        )
    self.ListSenders = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/ListSenders',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_sender__pb2.ListSendersRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_sender__pb2.ListSendersResponse.FromString,
        )
    self.GetSender = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/GetSender',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_sender__pb2.GetSenderRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_sender__pb2.Sender.FromString,
        )
    self.CreateSender = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/CreateSender',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_sender__pb2.CreateSenderRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_sender__pb2.Sender.FromString,
        )
    self.UpdateSender = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/UpdateSender',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_sender__pb2.UpdateSenderRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_sender__pb2.Sender.FromString,
        )
    self.DeleteSender = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/DeleteSender',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_sender__pb2.DeleteSenderRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_sender__pb2.Sender.FromString,
        )
    self.UndeleteSender = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/UndeleteSender',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_sender__pb2.UndeleteSenderRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_sender__pb2.Sender.FromString,
        )
    self.SendMessage = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/SendMessage',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_sender__pb2.SendMessageRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_sender__pb2.SendMessageResponse.FromString,
        )
    self.ListSmtpCredentials = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/ListSmtpCredentials',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_smtp__credential__pb2.ListSmtpCredentialsRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_smtp__credential__pb2.ListSmtpCredentialsResponse.FromString,
        )
    self.GetSmtpCredential = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/GetSmtpCredential',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_smtp__credential__pb2.GetSmtpCredentialRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_smtp__credential__pb2.SmtpCredential.FromString,
        )
    self.CreateSmtpCredential = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/CreateSmtpCredential',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_smtp__credential__pb2.CreateSmtpCredentialRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_smtp__credential__pb2.SmtpCredential.FromString,
        )
    self.UpdateSmtpCredential = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/UpdateSmtpCredential',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_smtp__credential__pb2.UpdateSmtpCredentialRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_smtp__credential__pb2.SmtpCredential.FromString,
        )
    self.DeleteSmtpCredential = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/DeleteSmtpCredential',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_smtp__credential__pb2.DeleteSmtpCredentialRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.ListReceiptRules = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/ListReceiptRules',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_receipt__rule__pb2.ListReceiptRulesRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_receipt__rule__pb2.ListReceiptRulesResponse.FromString,
        )
    self.GetReceiptRule = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/GetReceiptRule',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_receipt__rule__pb2.GetReceiptRuleRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_receipt__rule__pb2.ReceiptRule.FromString,
        )
    self.CreateReceiptRule = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/CreateReceiptRule',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_receipt__rule__pb2.CreateReceiptRuleRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_receipt__rule__pb2.ReceiptRule.FromString,
        )
    self.UpdateReceiptRule = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/UpdateReceiptRule',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_receipt__rule__pb2.UpdateReceiptRuleRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_receipt__rule__pb2.ReceiptRule.FromString,
        )
    self.DeleteReceiptRule = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/DeleteReceiptRule',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_receipt__rule__pb2.DeleteReceiptRuleRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.ListAddressSets = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/ListAddressSets',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_address__set__pb2.ListAddressSetsRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_address__set__pb2.ListAddressSetsResponse.FromString,
        )
    self.GetAddressSet = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/GetAddressSet',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_address__set__pb2.GetAddressSetRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_address__set__pb2.AddressSet.FromString,
        )
    self.CreateAddressSet = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/CreateAddressSet',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_address__set__pb2.CreateAddressSetRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_address__set__pb2.AddressSet.FromString,
        )
    self.UpdateAddressSet = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/UpdateAddressSet',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_address__set__pb2.UpdateAddressSetRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_address__set__pb2.AddressSet.FromString,
        )
    self.DeleteAddressSet = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/DeleteAddressSet',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_address__set__pb2.DeleteAddressSetRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_address__set__pb2.AddressSet.FromString,
        )
    self.UndeleteAddressSet = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/UndeleteAddressSet',
        request_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_address__set__pb2.UndeleteAddressSetRequest.SerializeToString,
        response_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_address__set__pb2.AddressSet.FromString,
        )
    self.GetIamPolicy = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/GetIamPolicy',
        request_serializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.GetIamPolicyRequest.SerializeToString,
        response_deserializer=google_dot_iam_dot_v1_dot_policy__pb2.Policy.FromString,
        )
    self.SetIamPolicy = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/SetIamPolicy',
        request_serializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.SetIamPolicyRequest.SerializeToString,
        response_deserializer=google_dot_iam_dot_v1_dot_policy__pb2.Policy.FromString,
        )
    self.TestIamPermissions = channel.unary_unary(
        '/google.cloud.mail.v1alpha3.CloudMail/TestIamPermissions',
        request_serializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.TestIamPermissionsRequest.SerializeToString,
        response_deserializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.TestIamPermissionsResponse.FromString,
        )


class CloudMailServicer(object):
  """Provides Google Cloud Mail customers a way to manage the service and to send
  mail.  Use this to add or remove domains, define handling for incoming
  messages, and register senders for outbound messages.
  """

  def ListDomains(self, request, context):
    """Lists domains with the given parent.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDomain(self, request, context):
    """Gets the specified domain.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateDomain(self, request, context):
    """Registers the specified domain for Cloud Mail.
    Cloudmail can provide a regional, per-project domain name e.g.
    my-project.us-east1.cloudsmtp.net
    where cloudmail manages all of the dns. These can be
    created by calling CreateDomain with Domain.project_domain == true
    and Domain.domain_name == "".
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateDomain(self, request, context):
    """Updates the given domain.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteDomain(self, request, context):
    """Marks a domain as deleted. It will be automatically expunged after 30 days
    unless it is undeleted with UndeleteDomain.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UndeleteDomain(self, request, context):
    """Removes the deleted status for a domain that was previously deleted with
    DeleteDomain.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TestReceiptRules(self, request, context):
    """Evaluates a recipient address against the domain's receipt ruleset and
    returns the list of rules that would fire.  Clients may provide an optional
    alternative candidate ruleset to be evaluated instead of the service's
    active ruleset.  This method can be used to verify Cloud Mail behavior for
    incoming messages.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VerifyDomain(self, request, context):
    """Checks the domain's DNS TXT record for the verification token, and updates
    the status to ACTIVE if valid.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListEmailVerifiedAddresses(self, request, context):
    """Lists EmailVerifiedAddresses with the given parent.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetEmailVerifiedAddress(self, request, context):
    """Gets the specified EmailVerifiedAddress.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateEmailVerifiedAddress(self, request, context):
    """Creates the given EmailVerifiedAddress.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateEmailVerifiedAddress(self, request, context):
    """Updates the given EmailVerifiedAddress.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteEmailVerifiedAddress(self, request, context):
    """Marks the specified EmailVerifiedAddress as deleted. It will be
    automatically expunged after 30 days unless it is undeleted with
    UndeleteEmailVerifiedAddress.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UndeleteEmailVerifiedAddress(self, request, context):
    """Undeletes the specified EmailVerifiedAddress.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RequestEmailVerification(self, request, context):
    """Emails a verification token to an unverified EmailVerifiedAddress.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VerifyEmail(self, request, context):
    """Checks token and verifies EmailVerifiedAddress
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListSenders(self, request, context):
    """Lists senders for the given parent.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSender(self, request, context):
    """Gets the specified sender.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateSender(self, request, context):
    """Creates the specified sender.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateSender(self, request, context):
    """Updates the specified sender.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteSender(self, request, context):
    """Marks the specified sender as deleted. It will be automatically expunged
    after 30 days unless it is undeleted with UndeleteSender.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UndeleteSender(self, request, context):
    """Undeletes the specified sender.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendMessage(self, request, context):
    """Sends a message using the specified sender.  The "From" address in the
    message headers must be a registered and verified domain with the service,
    and it must also match the sender's list of allowed "From" patterns;
    otherwise, the request will fail with a FAILED_PRECONDITION error.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListSmtpCredentials(self, request, context):
    """Lists SMTP credentials for the specified sender.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSmtpCredential(self, request, context):
    """Gets the specified SMTP credential.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateSmtpCredential(self, request, context):
    """Creates the specified SMTP credential.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateSmtpCredential(self, request, context):
    """Updates the specified SMTP credential.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteSmtpCredential(self, request, context):
    """Deletes the specified SMTP credential.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListReceiptRules(self, request, context):
    """Lists receipt rules for the specified Cloud Mail domain.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetReceiptRule(self, request, context):
    """Gets the specified receipt rule.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateReceiptRule(self, request, context):
    """Creates the specified receipt rule.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateReceiptRule(self, request, context):
    """Updates the specified receipt rule.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteReceiptRule(self, request, context):
    """Deletes the specified receipt rule.  If the rule is part of the domain's
    active ruleset, the rule reference is also removed from the ruleset.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListAddressSets(self, request, context):
    """Lists AddressSets for the specified Cloud Mail domain.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAddressSet(self, request, context):
    """Gets the specified AddressSet.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateAddressSet(self, request, context):
    """Creates the specified AddressSet.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateAddressSet(self, request, context):
    """Updates the specified AddressSet.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteAddressSet(self, request, context):
    """Marks the specified AddressSet as deleted. It will be automatically
    expunged after 30 days unless it is undeleted with UndeleteAddressSet.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UndeleteAddressSet(self, request, context):
    """Undeletes the specified AddressSet.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetIamPolicy(self, request, context):
    """Gets the access control policy for Cloud Mail resources.
    Returns an empty policy if the resource exists and does not have a policy
    set.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetIamPolicy(self, request, context):
    """Sets the access control policy for a Cloud Mail Resources. Replaces
    any existing policy.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TestIamPermissions(self, request, context):
    """Returns permissions that a caller has on a Cloud Mail Resource.
    If the resource does not exist, this will return an empty set of
    permissions, not a [NOT_FOUND][google.rpc.Code.NOT_FOUND] error.

    Note: This operation is designed to be used for building permission-aware
    UIs and command-line tools, not for authorization checking. This operation
    may "fail open" without warning.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CloudMailServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListDomains': grpc.unary_unary_rpc_method_handler(
          servicer.ListDomains,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.ListDomainsRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.ListDomainsResponse.SerializeToString,
      ),
      'GetDomain': grpc.unary_unary_rpc_method_handler(
          servicer.GetDomain,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.GetDomainRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.Domain.SerializeToString,
      ),
      'CreateDomain': grpc.unary_unary_rpc_method_handler(
          servicer.CreateDomain,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.CreateDomainRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.Domain.SerializeToString,
      ),
      'UpdateDomain': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateDomain,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.UpdateDomainRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.Domain.SerializeToString,
      ),
      'DeleteDomain': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteDomain,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.DeleteDomainRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.Domain.SerializeToString,
      ),
      'UndeleteDomain': grpc.unary_unary_rpc_method_handler(
          servicer.UndeleteDomain,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.UndeleteDomainRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.Domain.SerializeToString,
      ),
      'TestReceiptRules': grpc.unary_unary_rpc_method_handler(
          servicer.TestReceiptRules,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.TestReceiptRulesRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.TestReceiptRulesResponse.SerializeToString,
      ),
      'VerifyDomain': grpc.unary_unary_rpc_method_handler(
          servicer.VerifyDomain,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.VerifyDomainRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_domain__pb2.Domain.SerializeToString,
      ),
      'ListEmailVerifiedAddresses': grpc.unary_unary_rpc_method_handler(
          servicer.ListEmailVerifiedAddresses,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.ListEmailVerifiedAddressesRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.ListEmailVerifiedAddressesResponse.SerializeToString,
      ),
      'GetEmailVerifiedAddress': grpc.unary_unary_rpc_method_handler(
          servicer.GetEmailVerifiedAddress,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.GetEmailVerifiedAddressRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.EmailVerifiedAddress.SerializeToString,
      ),
      'CreateEmailVerifiedAddress': grpc.unary_unary_rpc_method_handler(
          servicer.CreateEmailVerifiedAddress,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.CreateEmailVerifiedAddressRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.EmailVerifiedAddress.SerializeToString,
      ),
      'UpdateEmailVerifiedAddress': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateEmailVerifiedAddress,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.UpdateEmailVerifiedAddressRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.EmailVerifiedAddress.SerializeToString,
      ),
      'DeleteEmailVerifiedAddress': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteEmailVerifiedAddress,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.DeleteEmailVerifiedAddressRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.EmailVerifiedAddress.SerializeToString,
      ),
      'UndeleteEmailVerifiedAddress': grpc.unary_unary_rpc_method_handler(
          servicer.UndeleteEmailVerifiedAddress,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.UndeleteEmailVerifiedAddressRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.EmailVerifiedAddress.SerializeToString,
      ),
      'RequestEmailVerification': grpc.unary_unary_rpc_method_handler(
          servicer.RequestEmailVerification,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.RequestEmailVerificationRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.RequestEmailVerificationResponse.SerializeToString,
      ),
      'VerifyEmail': grpc.unary_unary_rpc_method_handler(
          servicer.VerifyEmail,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.VerifyEmailRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_email__verified__address__pb2.EmailVerifiedAddress.SerializeToString,
      ),
      'ListSenders': grpc.unary_unary_rpc_method_handler(
          servicer.ListSenders,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_sender__pb2.ListSendersRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_sender__pb2.ListSendersResponse.SerializeToString,
      ),
      'GetSender': grpc.unary_unary_rpc_method_handler(
          servicer.GetSender,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_sender__pb2.GetSenderRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_sender__pb2.Sender.SerializeToString,
      ),
      'CreateSender': grpc.unary_unary_rpc_method_handler(
          servicer.CreateSender,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_sender__pb2.CreateSenderRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_sender__pb2.Sender.SerializeToString,
      ),
      'UpdateSender': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateSender,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_sender__pb2.UpdateSenderRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_sender__pb2.Sender.SerializeToString,
      ),
      'DeleteSender': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteSender,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_sender__pb2.DeleteSenderRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_sender__pb2.Sender.SerializeToString,
      ),
      'UndeleteSender': grpc.unary_unary_rpc_method_handler(
          servicer.UndeleteSender,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_sender__pb2.UndeleteSenderRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_sender__pb2.Sender.SerializeToString,
      ),
      'SendMessage': grpc.unary_unary_rpc_method_handler(
          servicer.SendMessage,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_sender__pb2.SendMessageRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_sender__pb2.SendMessageResponse.SerializeToString,
      ),
      'ListSmtpCredentials': grpc.unary_unary_rpc_method_handler(
          servicer.ListSmtpCredentials,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_smtp__credential__pb2.ListSmtpCredentialsRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_smtp__credential__pb2.ListSmtpCredentialsResponse.SerializeToString,
      ),
      'GetSmtpCredential': grpc.unary_unary_rpc_method_handler(
          servicer.GetSmtpCredential,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_smtp__credential__pb2.GetSmtpCredentialRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_smtp__credential__pb2.SmtpCredential.SerializeToString,
      ),
      'CreateSmtpCredential': grpc.unary_unary_rpc_method_handler(
          servicer.CreateSmtpCredential,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_smtp__credential__pb2.CreateSmtpCredentialRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_smtp__credential__pb2.SmtpCredential.SerializeToString,
      ),
      'UpdateSmtpCredential': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateSmtpCredential,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_smtp__credential__pb2.UpdateSmtpCredentialRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_smtp__credential__pb2.SmtpCredential.SerializeToString,
      ),
      'DeleteSmtpCredential': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteSmtpCredential,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_smtp__credential__pb2.DeleteSmtpCredentialRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'ListReceiptRules': grpc.unary_unary_rpc_method_handler(
          servicer.ListReceiptRules,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_receipt__rule__pb2.ListReceiptRulesRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_receipt__rule__pb2.ListReceiptRulesResponse.SerializeToString,
      ),
      'GetReceiptRule': grpc.unary_unary_rpc_method_handler(
          servicer.GetReceiptRule,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_receipt__rule__pb2.GetReceiptRuleRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_receipt__rule__pb2.ReceiptRule.SerializeToString,
      ),
      'CreateReceiptRule': grpc.unary_unary_rpc_method_handler(
          servicer.CreateReceiptRule,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_receipt__rule__pb2.CreateReceiptRuleRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_receipt__rule__pb2.ReceiptRule.SerializeToString,
      ),
      'UpdateReceiptRule': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateReceiptRule,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_receipt__rule__pb2.UpdateReceiptRuleRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_receipt__rule__pb2.ReceiptRule.SerializeToString,
      ),
      'DeleteReceiptRule': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteReceiptRule,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_receipt__rule__pb2.DeleteReceiptRuleRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'ListAddressSets': grpc.unary_unary_rpc_method_handler(
          servicer.ListAddressSets,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_address__set__pb2.ListAddressSetsRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_address__set__pb2.ListAddressSetsResponse.SerializeToString,
      ),
      'GetAddressSet': grpc.unary_unary_rpc_method_handler(
          servicer.GetAddressSet,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_address__set__pb2.GetAddressSetRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_address__set__pb2.AddressSet.SerializeToString,
      ),
      'CreateAddressSet': grpc.unary_unary_rpc_method_handler(
          servicer.CreateAddressSet,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_address__set__pb2.CreateAddressSetRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_address__set__pb2.AddressSet.SerializeToString,
      ),
      'UpdateAddressSet': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateAddressSet,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_address__set__pb2.UpdateAddressSetRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_address__set__pb2.AddressSet.SerializeToString,
      ),
      'DeleteAddressSet': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteAddressSet,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_address__set__pb2.DeleteAddressSetRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_address__set__pb2.AddressSet.SerializeToString,
      ),
      'UndeleteAddressSet': grpc.unary_unary_rpc_method_handler(
          servicer.UndeleteAddressSet,
          request_deserializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_address__set__pb2.UndeleteAddressSetRequest.FromString,
          response_serializer=google_dot_cloud_dot_mail__v1alpha3_dot_proto_dot_address__set__pb2.AddressSet.SerializeToString,
      ),
      'GetIamPolicy': grpc.unary_unary_rpc_method_handler(
          servicer.GetIamPolicy,
          request_deserializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.GetIamPolicyRequest.FromString,
          response_serializer=google_dot_iam_dot_v1_dot_policy__pb2.Policy.SerializeToString,
      ),
      'SetIamPolicy': grpc.unary_unary_rpc_method_handler(
          servicer.SetIamPolicy,
          request_deserializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.SetIamPolicyRequest.FromString,
          response_serializer=google_dot_iam_dot_v1_dot_policy__pb2.Policy.SerializeToString,
      ),
      'TestIamPermissions': grpc.unary_unary_rpc_method_handler(
          servicer.TestIamPermissions,
          request_deserializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.TestIamPermissionsRequest.FromString,
          response_serializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.TestIamPermissionsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'google.cloud.mail.v1alpha3.CloudMail', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
