# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/mail_v1alpha3/proto/smtp_credential.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/cloud/mail_v1alpha3/proto/smtp_credential.proto',
  package='google.cloud.mail.v1alpha3',
  syntax='proto3',
  serialized_pb=_b('\n6google/cloud/mail_v1alpha3/proto/smtp_credential.proto\x12\x1agoogle.cloud.mail.v1alpha3\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe0\x01\n\x0eSmtpCredential\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12/\n\x0b\x63reate_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0bupdate_time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1c\n\x14service_account_name\x18\x06 \x01(\t\x12\x1d\n\x15service_account_email\x18\x07 \x01(\t\",\n\x1aListSmtpCredentialsRequest\x12\x0e\n\x06parent\x18\x01 \x01(\t\"c\n\x1bListSmtpCredentialsResponse\x12\x44\n\x10smtp_credentials\x18\x01 \x03(\x0b\x32*.google.cloud.mail.v1alpha3.SmtpCredential\"(\n\x18GetSmtpCredentialRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x8e\x01\n\x1b\x43reateSmtpCredentialRequest\x12\x0e\n\x06parent\x18\x01 \x01(\t\x12\x1a\n\x12smtp_credential_id\x18\x02 \x01(\t\x12\x43\n\x0fsmtp_credential\x18\x03 \x01(\x0b\x32*.google.cloud.mail.v1alpha3.SmtpCredential\"\x93\x01\n\x1bUpdateSmtpCredentialRequest\x12\x43\n\x0fsmtp_credential\x18\x01 \x01(\x0b\x32*.google.cloud.mail.v1alpha3.SmtpCredential\x12/\n\x0bupdate_mask\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.FieldMask\"+\n\x1b\x44\x65leteSmtpCredentialRequest\x12\x0c\n\x04name\x18\x01 \x01(\tB\x80\x01\n\x1e\x63om.google.cloud.mail.v1alpha3B\x13smtpCredentialProtoP\x01Z>google.golang.org/genproto/googleapis/cloud/mail/v1alpha3;mail\xf8\x01\x01\xa2\x02\x03GCMb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_field__mask__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_SMTPCREDENTIAL = _descriptor.Descriptor(
  name='SmtpCredential',
  full_name='google.cloud.mail.v1alpha3.SmtpCredential',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='google.cloud.mail.v1alpha3.SmtpCredential.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='google.cloud.mail.v1alpha3.SmtpCredential.user_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='google.cloud.mail.v1alpha3.SmtpCredential.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='create_time', full_name='google.cloud.mail.v1alpha3.SmtpCredential.create_time', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='update_time', full_name='google.cloud.mail.v1alpha3.SmtpCredential.update_time', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service_account_name', full_name='google.cloud.mail.v1alpha3.SmtpCredential.service_account_name', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service_account_email', full_name='google.cloud.mail.v1alpha3.SmtpCredential.service_account_email', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=378,
)


_LISTSMTPCREDENTIALSREQUEST = _descriptor.Descriptor(
  name='ListSmtpCredentialsRequest',
  full_name='google.cloud.mail.v1alpha3.ListSmtpCredentialsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parent', full_name='google.cloud.mail.v1alpha3.ListSmtpCredentialsRequest.parent', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=424,
)


_LISTSMTPCREDENTIALSRESPONSE = _descriptor.Descriptor(
  name='ListSmtpCredentialsResponse',
  full_name='google.cloud.mail.v1alpha3.ListSmtpCredentialsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='smtp_credentials', full_name='google.cloud.mail.v1alpha3.ListSmtpCredentialsResponse.smtp_credentials', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=426,
  serialized_end=525,
)


_GETSMTPCREDENTIALREQUEST = _descriptor.Descriptor(
  name='GetSmtpCredentialRequest',
  full_name='google.cloud.mail.v1alpha3.GetSmtpCredentialRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='google.cloud.mail.v1alpha3.GetSmtpCredentialRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=527,
  serialized_end=567,
)


_CREATESMTPCREDENTIALREQUEST = _descriptor.Descriptor(
  name='CreateSmtpCredentialRequest',
  full_name='google.cloud.mail.v1alpha3.CreateSmtpCredentialRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parent', full_name='google.cloud.mail.v1alpha3.CreateSmtpCredentialRequest.parent', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='smtp_credential_id', full_name='google.cloud.mail.v1alpha3.CreateSmtpCredentialRequest.smtp_credential_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='smtp_credential', full_name='google.cloud.mail.v1alpha3.CreateSmtpCredentialRequest.smtp_credential', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=570,
  serialized_end=712,
)


_UPDATESMTPCREDENTIALREQUEST = _descriptor.Descriptor(
  name='UpdateSmtpCredentialRequest',
  full_name='google.cloud.mail.v1alpha3.UpdateSmtpCredentialRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='smtp_credential', full_name='google.cloud.mail.v1alpha3.UpdateSmtpCredentialRequest.smtp_credential', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='update_mask', full_name='google.cloud.mail.v1alpha3.UpdateSmtpCredentialRequest.update_mask', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=715,
  serialized_end=862,
)


_DELETESMTPCREDENTIALREQUEST = _descriptor.Descriptor(
  name='DeleteSmtpCredentialRequest',
  full_name='google.cloud.mail.v1alpha3.DeleteSmtpCredentialRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='google.cloud.mail.v1alpha3.DeleteSmtpCredentialRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=864,
  serialized_end=907,
)

_SMTPCREDENTIAL.fields_by_name['create_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_SMTPCREDENTIAL.fields_by_name['update_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_LISTSMTPCREDENTIALSRESPONSE.fields_by_name['smtp_credentials'].message_type = _SMTPCREDENTIAL
_CREATESMTPCREDENTIALREQUEST.fields_by_name['smtp_credential'].message_type = _SMTPCREDENTIAL
_UPDATESMTPCREDENTIALREQUEST.fields_by_name['smtp_credential'].message_type = _SMTPCREDENTIAL
_UPDATESMTPCREDENTIALREQUEST.fields_by_name['update_mask'].message_type = google_dot_protobuf_dot_field__mask__pb2._FIELDMASK
DESCRIPTOR.message_types_by_name['SmtpCredential'] = _SMTPCREDENTIAL
DESCRIPTOR.message_types_by_name['ListSmtpCredentialsRequest'] = _LISTSMTPCREDENTIALSREQUEST
DESCRIPTOR.message_types_by_name['ListSmtpCredentialsResponse'] = _LISTSMTPCREDENTIALSRESPONSE
DESCRIPTOR.message_types_by_name['GetSmtpCredentialRequest'] = _GETSMTPCREDENTIALREQUEST
DESCRIPTOR.message_types_by_name['CreateSmtpCredentialRequest'] = _CREATESMTPCREDENTIALREQUEST
DESCRIPTOR.message_types_by_name['UpdateSmtpCredentialRequest'] = _UPDATESMTPCREDENTIALREQUEST
DESCRIPTOR.message_types_by_name['DeleteSmtpCredentialRequest'] = _DELETESMTPCREDENTIALREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SmtpCredential = _reflection.GeneratedProtocolMessageType('SmtpCredential', (_message.Message,), dict(
  DESCRIPTOR = _SMTPCREDENTIAL,
  __module__ = 'google.cloud.mail_v1alpha3.proto.smtp_credential_pb2'
  ,
  __doc__ = """A credential for sending mail via the Cloud Mail SMTP relay service.
  Each sender may have up to five SMTP credentials.
  
  
  Attributes:
      name:
          The resource name for the SMTP credential, like
          "projects/1234/regions/us-
          east1/senders/abc/smtpCredentials/xyz". Read-only.
      user_id:
          The user id for SMTP authentication. Read-only.
      password:
          The password for SMTP authentication. Read-only, and only
          returned on Create. The caller must store the password
          returned by Create, since there is no way to recover it later.
          If the password is lost, a new SmtpCredential should be
          created.
      create_time:
          The creation timestamp.
      update_time:
          The last modified timestamp, set during create or update.
      service_account_name:
          google.iam.admin.v1.ServiceAccount.name
      service_account_email:
          google.iam.admin.v1.ServiceAccount.email
  """,
  # @@protoc_insertion_point(class_scope:google.cloud.mail.v1alpha3.SmtpCredential)
  ))
_sym_db.RegisterMessage(SmtpCredential)

ListSmtpCredentialsRequest = _reflection.GeneratedProtocolMessageType('ListSmtpCredentialsRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTSMTPCREDENTIALSREQUEST,
  __module__ = 'google.cloud.mail_v1alpha3.proto.smtp_credential_pb2'
  ,
  __doc__ = """Request for CloudMail.ListSmtpCredentials.
  
  
  Attributes:
      parent:
          Name of the sender whose SMTP credentials are to be retrieved,
          like "projects/1234/regions/us-east1/senders/abc".
  """,
  # @@protoc_insertion_point(class_scope:google.cloud.mail.v1alpha3.ListSmtpCredentialsRequest)
  ))
_sym_db.RegisterMessage(ListSmtpCredentialsRequest)

ListSmtpCredentialsResponse = _reflection.GeneratedProtocolMessageType('ListSmtpCredentialsResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTSMTPCREDENTIALSRESPONSE,
  __module__ = 'google.cloud.mail_v1alpha3.proto.smtp_credential_pb2'
  ,
  __doc__ = """Response for CloudMail.ListSmtpCredentials.
  
  
  Attributes:
      smtp_credentials:
          The SMTP credentials retrieved. The password field is not
          populated.
  """,
  # @@protoc_insertion_point(class_scope:google.cloud.mail.v1alpha3.ListSmtpCredentialsResponse)
  ))
_sym_db.RegisterMessage(ListSmtpCredentialsResponse)

GetSmtpCredentialRequest = _reflection.GeneratedProtocolMessageType('GetSmtpCredentialRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETSMTPCREDENTIALREQUEST,
  __module__ = 'google.cloud.mail_v1alpha3.proto.smtp_credential_pb2'
  ,
  __doc__ = """Request for CloudMail.GetSmtpCredential.
  
  
  Attributes:
      name:
          Name of the SMTP credential to retrieve, like
          "projects/1234/regions/us-
          east1/senders/abc/smtpCredentials/xyz".
  """,
  # @@protoc_insertion_point(class_scope:google.cloud.mail.v1alpha3.GetSmtpCredentialRequest)
  ))
_sym_db.RegisterMessage(GetSmtpCredentialRequest)

CreateSmtpCredentialRequest = _reflection.GeneratedProtocolMessageType('CreateSmtpCredentialRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATESMTPCREDENTIALREQUEST,
  __module__ = 'google.cloud.mail_v1alpha3.proto.smtp_credential_pb2'
  ,
  __doc__ = """Request for CloudMail.CreateSmtpCredential.
  
  
  Attributes:
      parent:
          Name of the sender to register the SMTP credential under, like
          "projects/1234/regions/us-east1/senders/abc".
      smtp_credential_id:
          The client-assigned name for the credential. The ID must be an
          ASCII string consisting only of uppercase and lowercase
          letters, digits, and hyphens. The maximum length is 128 bytes.
      smtp_credential:
          The SMTP credential to create.
  """,
  # @@protoc_insertion_point(class_scope:google.cloud.mail.v1alpha3.CreateSmtpCredentialRequest)
  ))
_sym_db.RegisterMessage(CreateSmtpCredentialRequest)

UpdateSmtpCredentialRequest = _reflection.GeneratedProtocolMessageType('UpdateSmtpCredentialRequest', (_message.Message,), dict(
  DESCRIPTOR = _UPDATESMTPCREDENTIALREQUEST,
  __module__ = 'google.cloud.mail_v1alpha3.proto.smtp_credential_pb2'
  ,
  __doc__ = """Request for CloudMail.UpdateSmtpCredential.
  
  
  Attributes:
      smtp_credential:
          The SMTP credential to update.
      update_mask:
          The fields to update. Required.
  """,
  # @@protoc_insertion_point(class_scope:google.cloud.mail.v1alpha3.UpdateSmtpCredentialRequest)
  ))
_sym_db.RegisterMessage(UpdateSmtpCredentialRequest)

DeleteSmtpCredentialRequest = _reflection.GeneratedProtocolMessageType('DeleteSmtpCredentialRequest', (_message.Message,), dict(
  DESCRIPTOR = _DELETESMTPCREDENTIALREQUEST,
  __module__ = 'google.cloud.mail_v1alpha3.proto.smtp_credential_pb2'
  ,
  __doc__ = """Request for CloudMail.DeleteSmtpCredential.
  
  
  Attributes:
      name:
          Name of the SMTP credential to delete, like
          "projects/1234/regions/us-
          east1/senders/abc/smtpCredentials/xyz".
  """,
  # @@protoc_insertion_point(class_scope:google.cloud.mail.v1alpha3.DeleteSmtpCredentialRequest)
  ))
_sym_db.RegisterMessage(DeleteSmtpCredentialRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\036com.google.cloud.mail.v1alpha3B\023smtpCredentialProtoP\001Z>google.golang.org/genproto/googleapis/cloud/mail/v1alpha3;mail\370\001\001\242\002\003GCM'))
# @@protoc_insertion_point(module_scope)
